spring:
  application:
    name: users-service
  data:
    mongodb:
      database: test_db
      host: mongodb
      port: 27017

server:
  port: 8100

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://eureka-server:8761/eureka}
